


<Project>
	
	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>SunSerega</Authors>
		<PackageOutputPath>$(MSBuildThisFileDirectory)\0Deployed</PackageOutputPath>
		
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!--<NoWarn>$(NoWarn);CS1591</NoWarn>-->
        
        <BuildFile>$(MSBuildProjectDirectory)\obj\build.txt</BuildFile>
        
        <GetPackageVersionDependsOn>
            GetPackageVersion;
            $(GetPackageVersionDependsOn)
        </GetPackageVersionDependsOn>
    </PropertyGroup>
    
    <Target Name="GetPackageVersion">
        <ReadLinesFromFile File="$(BuildFile)">
            <Output TaskParameter="Lines" PropertyName="BuildNumber" />
        </ReadLinesFromFile>
        
        <PropertyGroup>
            <PackageVersion>1.0.0.$(BuildNumber)</PackageVersion>
        </PropertyGroup>
    </Target>
    
    <Target Name="IncBuildVersion" BeforeTargets="Build">
        <PropertyGroup>
            <BuildNumber Condition="!Exists('$(BuildFile)')">0</BuildNumber>
        </PropertyGroup>
        
        <ReadLinesFromFile File="$(BuildFile)" Condition="Exists('$(BuildFile)')">
            <Output TaskParameter="Lines" PropertyName="BuildNumber" />
        </ReadLinesFromFile>
        
        <PropertyGroup>
            <BuildNumber>$([MSBuild]::Add($(BuildNumber), 1))</BuildNumber>
        </PropertyGroup>
        
        <WriteLinesToFile File="$(BuildFile)" Lines="$(BuildNumber)" Overwrite="true" />
    </Target>
    
</Project>


